<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">


<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    
    <title>22. Exceptions &mdash; Think Sharply with C#: How to Think like a Computer Scientist</title>
    
    <link rel="stylesheet" href="_static/style.css" type="text/css" />
    <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
    
    <script type="text/javascript">
      var DOCUMENTATION_OPTIONS = {
        URL_ROOT:    './',
        VERSION:     'Second Edition',
        COLLAPSE_INDEX: false,
        FILE_SUFFIX: '.html',
        HAS_SOURCE:  true
      };
    </script>
    <script type="text/javascript" src="_static/jquery.js"></script>
    <script type="text/javascript" src="_static/underscore.js"></script>
    <script type="text/javascript" src="_static/doctools.js"></script>
    <link rel="top" title="Think Sharply with C#: How to Think like a Computer Scientist" href="index.html" />
    <link rel="next" title="23. The .NET Framework" href="frameworkclasslib.html" />
    <link rel="prev" title="21. Recursion" href="recursion.html" /> 
  </head>
  <body role="document">
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="genindex.html" title="General Index"
             accesskey="I">index</a></li>
        <li class="right" >
          <a href="frameworkclasslib.html" title="23. The .NET Framework"
             accesskey="N">next</a> |</li>
        <li class="right" >
          <a href="recursion.html" title="21. Recursion"
             accesskey="P">previous</a> |</li>
        <li class="nav-item nav-item-0"><a href="index.html">Think Sharply with C#: How to Think like a Computer Scientist</a> &raquo;</li> 
      </ul>
    </div>

    <div class="document">
      <div class="documentwrapper">
          <div class="body" role="main">
            
  <div class="section" id="exceptions">
<h1>22. Exceptions<a class="headerlink" href="#exceptions" title="Permalink to this headline">¶</a></h1>
<div class="section" id="catching-exceptions">
<span id="index-0"></span><h2>22.1. Catching exceptions<a class="headerlink" href="#catching-exceptions" title="Permalink to this headline">¶</a></h2>
<p>Whenever a runtime error occurs, the system <strong>throws</strong> an <strong>exception</strong>.  When this
happens, an <code class="docutils literal"><span class="pre">Exception</span></code> object is created.  It holds details about what went
wrong, and where.  We use the word &#8220;throw&#8221; to describe what happens, as one might say
<em>&#8220;I&#8217;m throwing this problem at my boss&#8221;</em>, or <em>&#8220;I&#8217;m throwing this problem over the fence&#8221;</em>.</p>
<p>Unless we take some special action to <strong>catch</strong> and handle the problem, the program will
<em>crash</em> at this point.    For example, division by zero will throw an exception.
So will an array or list index out of bounds, or an attempt to use a file that
does not exist.</p>
<img alt="_images/DivideByZero.png" src="_images/DivideByZero.png" />
<p>The key to what we&#8217;re going to do here is given by the title bar of the
exception window in this image: the exception <em>&#8220;was unhandled by user code&#8221;</em>.
We&#8217;re about to see how we can handle it.</p>
<p>In the picture above, also on the title line, we&#8217;re also told what type of exception
was thrown, in this case a <code class="docutils literal"><span class="pre">DivideByZeroException</span></code>.</p>
<p>Sometimes we want to execute an operation that might throw an exception, but we
don&#8217;t want the program to crash. We can handle the exception using the
<code class="docutils literal"><span class="pre">try</span> <span class="pre">...</span> <span class="pre">catch</span></code> statement to &#8220;wrap&#8221; a region of code.</p>
<p>For example, we might ask our user to enter a name of a file and then we&#8217;ll try to
read from it. If the file doesn&#8217;t exist, we want to catch and handle the exception:</p>
<blockquote>
<div><div class="highlight-csharp"><table class="highlighttable"><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14</pre></div></td><td class="code"><div class="highlight"><pre><span class="kt">string</span> <span class="n">filename</span> <span class="p">=</span> <span class="n">textBox1</span><span class="p">.</span><span class="n">Text</span><span class="p">;</span>
<span class="hll"><span class="k">try</span>
</span><span class="p">{</span>
    <span class="kt">string</span> <span class="n">content</span> <span class="p">=</span> <span class="n">File</span><span class="p">.</span><span class="n">ReadAllText</span><span class="p">(</span><span class="n">filename</span><span class="p">);</span>
    <span class="c1">/// do other useful things with the content</span>
    <span class="c1">/// ...</span>
<span class="p">}</span>
<span class="hll"><span class="k">catch</span> <span class="p">(</span><span class="n">Exception</span> <span class="n">ex</span><span class="p">)</span>
</span><span class="p">{</span>
    <span class="kt">string</span> <span class="n">msg</span> <span class="p">=</span> <span class="kt">string</span><span class="p">.</span><span class="n">Format</span><span class="p">(</span><span class="s">&quot;Reading file {0} threw an exception: \n{1}&quot;</span><span class="p">,</span>
          <span class="n">filename</span><span class="p">,</span> <span class="n">ex</span><span class="p">);</span>
    <span class="n">MessageBox</span><span class="p">.</span><span class="n">Show</span><span class="p">(</span><span class="n">msg</span><span class="p">);</span>
<span class="p">}</span>
<span class="p">...</span>
</pre></div>
</td></tr></table></div>
</div></blockquote>
<p>The <code class="docutils literal"><span class="pre">try</span> <span class="pre">...</span> <span class="pre">catch</span></code> statement consists of a try block followed by one or more catch clauses, which specify
handlers for different types of exceptions.  Each catch clause has an associated block of code.</p>
<p><code class="docutils literal"><span class="pre">try</span></code> executes and monitors the statements in the first block (lines 3-7). If no
exception is thrown, it skips any <code class="docutils literal"><span class="pre">catch</span></code> clauses and continues execution
(at line 14 in this example).
If any exception occurs, information about the error is packed into a
new exception object, and the exception is thrown.  In this example, the exception
is caught at line 8, and is assigned to variable <code class="docutils literal"><span class="pre">ex</span></code>.
Control immediately jumps into the <code class="docutils literal"><span class="pre">catch</span></code> block, where we execute lines 10-12.
When the block completes, execution continues at line 14 in this example.</p>
<p>Within the catch block, object <code class="docutils literal"><span class="pre">ex</span></code> is like any other parameter we&#8217;ve encountered:
it has a type, it has some properties, and it has some methods, and you can choose
your own variable name for it.  If you&#8217;re inquisitive about what else is inside an
exception object, set a breakpoint at line 10 and use the debugging tools to inspect it.</p>
</div>
<div class="section" id="we-can-catch-exceptions-that-occur-in-methods-we-ve-called">
<h2>22.2. We can catch exceptions that occur in methods we&#8217;ve called<a class="headerlink" href="#we-can-catch-exceptions-that-occur-in-methods-we-ve-called" title="Permalink to this headline">¶</a></h2>
<p>As our software becomes more complex we attempt to manage the complexity by
breaking it into methods (and coming soon) separate objects, and perhaps even
separate libraries.</p>
<p>Suppose your method <code class="docutils literal"><span class="pre">P</span></code> has a <code class="docutils literal"><span class="pre">try</span> <span class="pre">...</span> <span class="pre">catch</span></code> statement to catch exceptions.
<code class="docutils literal"><span class="pre">P</span></code> calls method <code class="docutils literal"><span class="pre">Q</span></code> which calls <code class="docutils literal"><span class="pre">W</span></code>.  But <code class="docutils literal"><span class="pre">W</span></code> throws a <code class="docutils literal"><span class="pre">FileNotFoundException</span></code>.
What happens next?</p>
<p>If <code class="docutils literal"><span class="pre">W</span></code> does not catch the exception, it exits immediately, and the exception is
thrown up to its caller <code class="docutils literal"><span class="pre">Q</span></code>.  If <code class="docutils literal"><span class="pre">Q</span></code> can&#8217;t catch it, the same happens again,
with the exception thrown up to <code class="docutils literal"><span class="pre">P</span></code>.  Now because <code class="docutils literal"><span class="pre">P</span></code> has a <code class="docutils literal"><span class="pre">catch</span></code>, it can recover.</p>
<p>We call the process of exiting all the called methods until we find one that is willing
to catch our exception <em>unwinding the call stack</em>.</p>
<p>So the important idea is that a <code class="docutils literal"><span class="pre">try</span> <span class="pre">...</span> <span class="pre">catch</span></code> statement can catch exceptions that
occur, even if they occur indirectly in other methods that are called from the wrapped
statements.</p>
<p>We&#8217;ll need some care, though. In the example above we caught the exception at line 8, with
an assumption that it was line 4 that caused the fault.  But in fact lines 5 or 6, or any
methods called by them could be our culprit.</p>
</div>
<div class="section" id="the-exception-hierarchy">
<span id="index-1"></span><h2>22.3. The Exception Hierarchy<a class="headerlink" href="#the-exception-hierarchy" title="Permalink to this headline">¶</a></h2>
<p>In Section 13.4 we introduced the idea that classes, or types, were organized
hierarchically via a system of inheritance.
We saw that an <code class="docutils literal"><span class="pre">Ellipse</span></code> object is-a kind of <code class="docutils literal"><span class="pre">Shape</span></code> object which is-a kind of <code class="docutils literal"><span class="pre">UIElement</span></code>.</p>
<p>Exception types are also organized hierarchically.  Here is a small fragment
diagram showing just a few possible types of exception.</p>
<img alt="_images/hierarchy.png" src="_images/hierarchy.png" />
<p>A <code class="docutils literal"><span class="pre">catch</span></code> can only catch certain kinds of exception.  In line 8 in our example, we
offered to catch anything of type <code class="docutils literal"><span class="pre">Exception</span></code>.  That is the most general type of
exception, and because <code class="docutils literal"><span class="pre">FileNotFoundException</span></code> is-a <code class="docutils literal"><span class="pre">Exception</span></code>, our <code class="docutils literal"><span class="pre">catch</span></code> will catch it.</p>
<p>But you can (and are generally encouraged) to catch specific exception types.  Consider this
fragment of code:</p>
<blockquote>
<div><div class="highlight-csharp"><table class="highlighttable"><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10</pre></div></td><td class="code"><div class="highlight"><pre><span class="k">try</span>
<span class="p">{</span>
    <span class="p">...</span>
<span class="p">}</span>
<span class="k">catch</span> <span class="p">(</span><span class="n">FileNotFoundException</span> <span class="n">ex1</span><span class="p">)</span>
<span class="p">{</span>  <span class="p">...</span> <span class="p">}</span>
<span class="k">catch</span> <span class="p">(</span><span class="n">DirectoryNotFoundException</span> <span class="n">ex2</span><span class="p">)</span>
<span class="p">{</span>  <span class="p">...</span> <span class="p">}</span>
<span class="k">catch</span> <span class="p">(</span><span class="n">IOException</span> <span class="n">ex3</span><span class="p">)</span>
<span class="p">{</span>  <span class="p">...</span> <span class="p">}</span>
</pre></div>
</td></tr></table></div>
</div></blockquote>
<p>Here we&#8217;re offering to catch three different kinds of exceptions
(so our <code class="docutils literal"><span class="pre">try</span></code> can have multiple <code class="docutils literal"><span class="pre">catch</span></code> clauses), but we wouldn&#8217;t catch
a <code class="docutils literal"><span class="pre">DivideByZeroException</span></code> if one occurred, either on line 3, or in some method
called indirectly by line 3.</p>
<p>Notice too that line 9 catches <code class="docutils literal"><span class="pre">IOException</span></code>.  Although <code class="docutils literal"><span class="pre">FileNotFoundException</span></code>
is-a <code class="docutils literal"><span class="pre">IOException</span></code>, it won&#8217;t be caught at line 9 &#8212; it will get caught instead at
line 5.  The <code class="docutils literal"><span class="pre">catch</span></code> clauses are examined in the order that we write them, top-to-bottom.</p>
<p>The very readable Microsoft
documentation at  <a class="reference external" href="http://msdn.microsoft.com/en-us/library/vstudio/0yd65esw.aspx">http://msdn.microsoft.com/en-us/library/vstudio/0yd65esw.aspx</a> says</p>
<blockquote>
<div>It is possible to use more than one specific catch clause in the
same <code class="docutils literal"><span class="pre">try</span> <span class="pre">...</span> <span class="pre">catch</span></code> statement. In this case, the order of the catch
clauses is important because the catch clauses are examined in
order. Catch the more specific exceptions before the less
specific ones. The compiler produces an error if you order
your catch blocks so that a later block can never be reached.</div></blockquote>
<p>A good guideline is to only catch the exceptions that you can recover
from.  For example, if your user is entering the name of the
file to open, they&#8217;re going to get it wrong sometimes.
Perhaps catch <code class="docutils literal"><span class="pre">FileNotFoundException</span></code>, or the more general <code class="docutils literal"><span class="pre">IOException</span></code>.</p>
<p>There is a trade-off, though.  If you catch the general exception you might
be able to sidestep a wider range of problems.  For example we might try to
open a file that is already in use by another program, or perhaps the file is
on a network drive and we have a timeout because the network fails temporarily.
If you catch the general exception, you&#8217;ll be able to recover from all these
cases, however, you won&#8217;t be able to react uniquely to each cause of the error.</p>
</div>
<div class="section" id="throwing-our-own-exceptions">
<span id="index-2"></span><h2>22.4. Throwing our own exceptions<a class="headerlink" href="#throwing-our-own-exceptions" title="Permalink to this headline">¶</a></h2>
<p>So far, run time errors throw exceptions.  But there doesn&#8217;t always have
to be an error.  Our program can deliberately use a <code class="docutils literal"><span class="pre">throw</span></code> statement
to throw an exceptions. Here is a method that expects a non-empty
<code class="docutils literal"><span class="pre">List&lt;int&gt;</span></code> from the caller, and it finds the maximum:</p>
<blockquote>
<div><div class="highlight-csharp"><table class="highlighttable"><tr><td class="linenos"><div class="linenodiv"><pre> 1
 2
 3
 4
 5
 6
 7
 8
 9
10
11
12
13
14
15
16
17</pre></div></td><td class="code"><div class="highlight"><pre> <span class="k">private</span> <span class="kt">int</span> <span class="nf">findMax</span><span class="p">(</span><span class="n">List</span><span class="p">&lt;</span><span class="kt">int</span><span class="p">&gt;</span> <span class="n">xs</span><span class="p">)</span>
 <span class="p">{</span>
     <span class="k">if</span> <span class="p">(</span><span class="n">xs</span><span class="p">.</span><span class="n">Count</span> <span class="p">==</span> <span class="m">0</span><span class="p">)</span>
     <span class="p">{</span>
<span class="hll">         <span class="n">Exception</span> <span class="n">myBad</span> <span class="p">=</span> <span class="k">new</span> <span class="n">InvalidOperationException</span><span class="p">(</span><span class="s">&quot;Cannot find max of an empty list.&quot;</span><span class="p">);</span>
</span><span class="hll">         <span class="k">throw</span> <span class="n">myBad</span><span class="p">;</span>
</span>     <span class="p">}</span>
     <span class="kt">int</span> <span class="n">result</span> <span class="p">=</span> <span class="n">xs</span><span class="p">[</span><span class="m">0</span><span class="p">];</span>
     <span class="k">for</span> <span class="p">(</span><span class="kt">int</span> <span class="n">i</span> <span class="p">=</span> <span class="m">0</span><span class="p">;</span> <span class="n">i</span> <span class="p">&lt;</span> <span class="n">xs</span><span class="p">.</span><span class="n">Count</span><span class="p">;</span> <span class="n">i</span><span class="p">++)</span>
     <span class="p">{</span>
         <span class="k">if</span> <span class="p">(</span><span class="n">xs</span><span class="p">[</span><span class="n">i</span><span class="p">]</span> <span class="p">&gt;</span> <span class="n">result</span><span class="p">)</span>
         <span class="p">{</span>
             <span class="n">result</span> <span class="p">=</span> <span class="n">xs</span><span class="p">[</span><span class="n">i</span><span class="p">];</span>
         <span class="p">}</span>
     <span class="p">}</span>
     <span class="k">return</span> <span class="n">result</span><span class="p">;</span>
 <span class="p">}</span>
</pre></div>
</td></tr></table></div>
</div></blockquote>
<p>Line 5 creates an exception object
which encapsulates specific information about the error, and line 6 throws
the exception.</p>
<p><code class="docutils literal"><span class="pre">InvalidOperationException</span></code> is one of the built-in exception types that seem
to most closely match the kind of error we want to raise.</p>
<p>If the method that called <code class="docutils literal"><span class="pre">findMax</span></code> (or its caller, or their caller, ...)
handles the error, then the program can
carry on running; otherwise the program crashes.</p>
<img alt="_images/own_exception.png" src="_images/own_exception.png" />
<p>The error message includes the exception type and the additional information
that was provided when the exception object was first created.</p>
<p>It is often the case that lines 193 and 194 (creating the exception object, then raising
the exception) are combined into a single statement, but there are really two different
and independent things happening, so perhaps it makes sense to keep the two
steps separate when we first learn to work with exceptions.
Here we show it all in a single statement:</p>
<blockquote>
<div><div class="highlight-csharp"><table class="highlighttable"><tr><td class="linenos"><div class="linenodiv"><pre>1</pre></div></td><td class="code"><div class="highlight"><pre> <span class="k">throw</span> <span class="k">new</span> <span class="nf">InvalidOperationException</span><span class="p">(</span><span class="s">&quot;Cannot find max of an empty list.&quot;</span><span class="p">);</span>
</pre></div>
</td></tr></table></div>
</div></blockquote>
</div>
<div class="section" id="glossary">
<h2>22.5. Glossary<a class="headerlink" href="#glossary" title="Permalink to this headline">¶</a></h2>
<dl class="glossary docutils">
<dt id="term-catch-an-exception">catch an exception</dt>
<dd>Instead of the default behaviour of having our program crash, we can
catch and recover from exceptions by wrapping regions of code
in a <code class="docutils literal"><span class="pre">try</span></code> ... <code class="docutils literal"><span class="pre">catch</span></code> statement.</dd>
<dt id="term-exception">exception</dt>
<dd>An error that occurs at runtime.   We say the exception is <em>thrown</em>.</dd>
<dt id="term-exception-hierarchy">exception hierarchy</dt>
<dd>Different types of exceptions are already defined in C#.
The types of exceptions are organized into a hierarchical (tree-like) type structure,
so, for example, an <code class="docutils literal"><span class="pre">FileNotFoundException</span></code> is-a kind of <code class="docutils literal"><span class="pre">IOException</span></code>
which is-a kind of <code class="docutils literal"><span class="pre">SystemException</span></code>, which is-a kind of <code class="docutils literal"><span class="pre">Exception</span></code>.</dd>
<dt id="term-is-a">is-a</dt>
<dd>A made-up word that Computer Scientists use to describe
a relationship between a more specific type and a more general type.
A Toyota is-a car.</dd>
<dt id="term-throw-statement"><code class="docutils literal"><span class="pre">throw</span></code> statement</dt>
<dd>A C# statement that allows us to throw exceptions from our code.</dd>
<dt id="term-unwinding-the-call-stack">unwinding the call stack</dt>
<dd>The process of exiting all the called methods until we find one that is willing to catch our exception.
If the method which throws an error is unable to handle it we will
exit that method and return to the call-site to see if the
caller is able to catch the exception. If it cannot, we will
continue to exit called methods until one is
found which can handle the exception or the pogram crashes.</dd>
</dl>
</div>
<div class="section" id="exercises">
<h2>22.6. Exercises<a class="headerlink" href="#exercises" title="Permalink to this headline">¶</a></h2>
<ol class="arabic">
<li><p class="first">Create a GUI with a textbox for entering a month number. The number is valid
if it is an integer between 1 and 12.  Convert what the user enters to an integer,
and validate that the number is between 1 and 12.  If not, pop up a MessageBox that
describes the problem, and ask the user to try again.  Catch any cases where the
user enters invalid characters, floating point numbers, leaves the text box blank, etc.</p>
</li>
<li><p class="first">Your car can break down in various ways.  Make a list of at least 15 different ways
(e.g. flat tyre, no fuel, door fell off, battery flat, won&#8217;t start, license expired,
crashed into lamp pole, repossessed by bank, etc.)
Google may be able to help if you ask the right question.</p>
<p>Now organize these problems into a hierarchy of <code class="docutils literal"><span class="pre">BreakDown</span></code> exceptions.  Draw
a tree diagram like the one in this chapter to show these relationships.</p>
</li>
</ol>
</div>
</div>


          </div>
      </div>
      <div class="clearer"></div>
    </div>
    <div class="related" role="navigation" aria-label="related navigation">
      <h3>Navigation</h3>
      <ul>
        <li class="right" style="margin-right: 10px">
          <a href="genindex.html" title="General Index"
             >index</a></li>
        <li class="right" >
          <a href="frameworkclasslib.html" title="23. The .NET Framework"
             >next</a> |</li>
        <li class="right" >
          <a href="recursion.html" title="21. Recursion"
             >previous</a> |</li>
        <li class="nav-item nav-item-0"><a href="index.html">Think Sharply with C#: How to Think like a Computer Scientist</a> &raquo;</li> 
      </ul>
    </div> 
  <div class="footer"> 
   <span class="creativecommons"> 
    <a href="http://creativecommons.org/licenses/by-nc-sa/3.0/" > 
      <img src="_static/creativecommons-88x31.png" 
           border="0" alt="Creative Commons License"/> 
     </a> 
    Licensed under a 
    <a href="http://creativecommons.org/licenses/by-nc-sa/3.0/"> 
    Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License. 
    </a> 
   </span> 
  </div>
  </body>
</html>